# Generated by Django 3.0.8 on 2022-02-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='D355-M984', max_length=100)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', max_length=13)),
                ('weight_limit', models.FloatField(verbose_name='Weight Limit(gr)')),
                ('battery_capacity', models.PositiveIntegerField(verbose_name='Battery Capacity(%)')),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=10)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aspirine', max_length=30)),
                ('weight', models.FloatField()),
                ('code', models.CharField(default='MED_56912', max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messanger.Drone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
