# Generated by Django 3.0.8 on 2022-02-20 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messanger', '0002_auto_20220218_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(default='D355-M984', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(default='MED_56912', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]$', 'format invalid')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(default='Aspirine', max_length=30, validators=[django.core.validators.RegexValidator('^[\\w-]$', 'format invalid')]),
        ),
    ]
