# Generated by Django 3.0.8 on 2022-02-20 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messanger', '0004_auto_20220220_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(default='MED_56912', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\_]+$', 'format invalid')]),
        ),
    ]
