# Generated by Django 3.0.8 on 2022-02-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messanger', '0005_auto_20220220_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
