# Generated by Django 3.0.8 on 2022-02-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messanger', '0006_auto_20220221_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='Messanger.Drone'),
        ),
    ]
