# Generated by Django 3.0.8 on 2022-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messanger', '0007_auto_20220222_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
