# Generated by Django 3.0.8 on 2022-02-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messanger', '0008_auto_20220224_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeToHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
